import sqlite3
import os

DB_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), "pulseintel.db")

def get_connection():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn

def init_db():
    conn = get_connection()
    cursor = conn.cursor()

    # Track 1: raw job postings
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS job_postings (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            company TEXT NOT NULL,
            title TEXT NOT NULL,
            location TEXT,
            source_url TEXT,
            source_site TEXT,
            hash TEXT UNIQUE,
            scraped_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            analyzed INTEGER DEFAULT 0
        )
    """)

       # Track 1: strategy briefs generated by Claude
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS strategy_briefs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            company TEXT NOT NULL,
            signal TEXT,
            intel TEXT,
            confidence TEXT,
            expected_timeline TEXT,
            jobs_analyzed INTEGER,
            threat_to_competitors TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)

    # Track 3: raw brand mentions
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS brand_mentions (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            brand TEXT NOT NULL,
            source_url TEXT,
            mention_type TEXT,
            raw_content TEXT,
            hash TEXT UNIQUE,
            scraped_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            analyzed INTEGER DEFAULT 0
        )
    """)

    # Track 3: threat alerts generated by Claude
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS threat_alerts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            brand TEXT NOT NULL,
            threat_type TEXT,
            risk_level TEXT,
            risk_score INTEGER,
            source_url TEXT,
            summary TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)

    conn.commit()
    conn.close()
    print("✅ Database initialized successfully.")
    print(f"📁 Database location: {DB_PATH}")

def mark_jobs_analyzed(company: str):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
        UPDATE job_postings
        SET analyzed = 1
        WHERE company = ? AND analyzed = 0
    """, (company,))
    conn.commit()
    conn.close()

def mark_mentions_analyzed(brand: str):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
        UPDATE brand_mentions
        SET analyzed = 1
        WHERE brand = ? AND analyzed = 0
    """, (brand,))
    conn.commit()
    conn.close()

if __name__ == "__main__":
    init_db()